spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:30534/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

#  server:
#    port: ${PORT:8080}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # validate | update | crete | crete-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect