spring:
  datasource:
    url: jdbc:postgresql://shinkansen.proxy.rlwy.net:58912/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  server:
      port:${PORT:8080}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect